apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo
  region: ap-southeast-1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
    roleName: cluster-autoscaler
    roleOnly: true

managedNodeGroups:
  - name: demo-nodegroup
    instanceType: t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    privateNetworking: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/demo: "owned"
