apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-cluster
  region: ap-southeast-1

vpc:
  id: ""  
  cidr: ""    
  subnets:
    private:
      ap-southeast-1a:
        id: ""
        cidr: "" 

      ap-southeast-1b:
        id: ""
        cidr: ""
    public:
      ap-southeast-1a:
        id: ""
        cidr: "" 

      ap-southeast-1b:
        id: ""
        cidr: ""