apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-cluster
  region: ap-southeast-1

managedNodeGroups:
  - name: managed-kubernetes-ng
    amiFamily: AmazonLinux2
    instanceType: m5.large
    minSize: 1
    desiredCapacity: 1
    maxSize: 2