apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-cluster
  region: us-west-2

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    instanceType: t2.large