---
- name: setup application server
  hosts: dbservers
  become: true
  become_method: sudo

  tasks:
    - name: install basic tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - curl
        - unzip