---
- name: setup application server
  hosts: dbservers
  become: true
  become_method: sudo

  tasks:
    - name: Install basic tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - curl
        - unzip
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    
    - name: Install Docker Module for Python
      pip:
        name: docker

