---
- name:  provisioning EC2 instances using Ansible
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
	keypair: AnsbileMaster2
	instance_type: t2.small
	image: ami-04ff9e9b51c1f62ca
	wait: yes
	group: webserver
	count: 1
	region: ap-southeast-1
	security_group: BasicEC2ServerGroup

  tasks:

    -   name: Launch the new EC2 Instance
		amazon.aws.ec2:
			key_name: "{{ keypair }}"
			group: "{{ security_group }}"
			instance_type: "{{ instance_type }}"
			image: "{{ image }}"
			wait: true
			region: "{{ region }}"
		register: ec2

    - 	name: Add Tagging to EC2 instance
		ec2_tag:
			resource= {{ item.id }} 
			region= {{ region }} 
			state=present
		with_items: "{{ ec2.instances }}"
		args:
			tags:
				Name: MyTargetEc2Instance
