apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: ap-southeast-1

managedNodeGroups:
  - name: demo-nodegroup
    instanceType: t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true
