- name: Update packages informations
  package_facts:
    manager: "auto"

- name: Display all installed packages informations
  debug:
    msg: "{{ ansible_facts.packages }}"

- name: Display all Chromium package informations
  debug:
    msg: "{{ ansible_facts.packages['chromium'] }}"
  when: "'chromium' in ansible_facts.packages"